﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace MLPrediction
{
    public partial class MLModel1
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Text.FeaturizeText(@"title", @"title")      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"text", @"text"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"subject", @"subject"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"date", @"date"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"title",@"text",@"subject",@"date"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(@"result", @"result"))      
                                    .Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))      
                                    .Append(mlContext.MulticlassClassification.Trainers.LbfgsMaximumEntropy(l1Regularization:0.893117728399576F,l2Regularization:1.13859524070714F,labelColumnName:@"result",featureColumnName:@"Features"))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(@"PredictedLabel", @"PredictedLabel"));

            return pipeline;
        }
    }
}
